ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EMERGENCY_OFFER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EMERGENCY_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EMERGENCY_DECLINED';
