"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import PostCard from "@/components/PostCard";

const sections = [
 ["overview","Overview"],["attention","Needs Attention"],["users","Users"],["content","Feed"],
 ["reports","Reports"],["emergencies","Emergencies"],["audit","Audit"],["broadcast","Broadcast"],["governance","Governance"]
] as const;
type Section=typeof sections[number][0];

function Btn({children,onClick,danger=false,disabled=false}:{children:any;onClick:()=>void;danger?:boolean;disabled?:boolean}){
 return <button disabled={disabled} onClick={onClick} className={danger?"rounded-lg border border-red-500/20 bg-red-500/[.06] px-3 py-2 text-xs font-semibold text-red-200 disabled:opacity-30":"rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs font-semibold text-white/65 hover:text-white disabled:opacity-30"}>{children}</button>
}

export default function ControlCenterClient({initialStats,superAdmin}:{initialStats:any;superAdmin:boolean}){
 const router=useRouter();
 const [section,setSection]=useState<Section>("overview"); const [data,setData]=useState<any>({stats:initialStats});
 const [q,setQ]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const [selected,setSelected]=useState<any>(null); const [confirm,setConfirm]=useState<{action:string;label:string}|null>(null);
 const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [href,setHref]=useState(""); const [reason,setReason]=useState(""); const [userSuggestions,setUserSuggestions]=useState<any[]>([]); const [postSuggestions,setPostSuggestions]=useState<any[]>([]);

 async function load(s=section){const r=await fetch("/api/control-center?section="+s+(q?"&q="+encodeURIComponent(q):""),{cache:"no-store"});setData(await r.json());}
 useEffect(()=>{void load()},[section]);
 useEffect(()=>{if(section!=="users"||q.trim().length<2){setUserSuggestions([]);return;} const timer=setTimeout(async()=>{const r=await fetch("/api/control-center?section=users&q="+encodeURIComponent(q.trim()),{cache:"no-store"});const d=await r.json();setUserSuggestions((d.users||[]).slice(0,6));},180);return()=>clearTimeout(timer)},[q,section]);
 useEffect(()=>{if(section!=="content"||q.trim().length<2){setPostSuggestions([]);return;} const timer=setTimeout(async()=>{const r=await fetch("/api/control-center?section=content&q="+encodeURIComponent(q.trim()),{cache:"no-store"});const d=await r.json();setPostSuggestions((d.posts||[]).slice(0,6));},180);return()=>clearTimeout(timer)},[q,section]);

 async function act(action:string,extra:any={}){
  setBusy(true);setMessage("Working...");
  const r=await fetch("/api/control-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,targetId:selected?.id,reason,...extra})});
  const d=await r.json();setMessage(r.ok?(d.sent?"Sent to "+d.sent+" users.":"Done."):(d.error||"Action failed."));
  setBusy(false);setConfirm(null);setSelected(null);setReason("");if(r.ok)void load();
 }
 function guarded(action:string,label:string){setReason("");setConfirm({action,label});}

 return <div className="mt-7">
  <div className="grid gap-5 lg:grid-cols-[190px_1fr]">
   <aside className="lg:sticky lg:top-6 lg:h-fit">
    <div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-2">
     <p className="px-3 pb-2 pt-2 text-[9px] font-black uppercase tracking-[.2em] text-red-300/60">Command</p>
     {sections.map(([id,label])=><button key={id} onClick={()=>{setSection(id);setSelected(null)}} className={section===id?"mb-1 flex w-full items-center rounded-xl bg-red-500/10 px-3 py-2.5 text-left text-xs font-bold text-red-100":"mb-1 flex w-full items-center rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-white/40 hover:bg-white/[.04] hover:text-white"}>{label}</button>)}
    </div>
    <div className="mt-3 rounded-2xl border border-red-500/15 bg-red-500/[.035] p-4"><p className="text-[9px] font-black uppercase tracking-[.18em] text-red-300">Authority</p><p className="mt-2 text-sm font-black">{superAdmin?"SUPER ADMIN":"ADMIN"}</p><p className="mt-1 text-[10px] leading-4 text-white/30">Use only for legitimate platform operations. Actions are audited.</p></div>
   </aside>

   <section className="min-w-0">
    {section==="attention"&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Reports",data.attention?.reports,"reports"],["Reported posts",data.attention?.reportedPosts,"content"],["Active emergencies",data.attention?.emergencies,"emergencies"]].map(([label,count,target]:any)=><button key={label} onClick={()=>setSection(target)} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5 text-left hover:bg-white/[.045]"><p className="text-[9px] uppercase tracking-[.18em] text-white/30">{label}</p><p className="mt-2 text-3xl font-black">{String(count??0)}</p><p className="mt-2 text-[10px] text-red-300/60">Review now →</p></button>)}</div><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-sm font-bold">Needs Attention</p><p className="mt-2 text-xs leading-5 text-white/35">This queue is intentionally small. It points you toward content that may require action instead of flooding the console with every record on Revvam.</p></div></div>}

    {section==="overview"&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.stats||{}).map(([k,v])=><div key={k} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><p className="text-[9px] uppercase tracking-[.18em] text-white/25">{k}</p><p className="mt-2 text-2xl font-black">{String(v)}</p></div>)}</div><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-sm font-bold">Command overview</p><p className="mt-2 max-w-2xl text-xs leading-5 text-white/35">Manage accounts, content, reports, emergencies, platform announcements and administrative history from one protected console. Destructive actions require confirmation.</p></div></div>}

    {(section==="users"||section==="content")&&<div>
     <div className="relative mb-4 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(section==="users"?"users":"content")} placeholder={section==="users"?"Search users by name, @username or email...":"Search posts, captions or usernames..."} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm outline-none"/><Btn onClick={()=>load(section==="users"?"users":"content")}>Search</Btn>{section==="users"&&userSuggestions.length>0&&<div className="absolute left-0 right-14 top-[calc(100%+6px)] z-40 overflow-hidden rounded-2xl border border-white/10 bg-[#0b0b0b]/98 p-1 shadow-2xl backdrop-blur-xl">{userSuggestions.map((u:any)=><button key={u.id} onClick={()=>{setQ(u.username);setUserSuggestions([]);router.push("/users/"+encodeURIComponent(u.username));}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left hover:bg-white/[.05]"><img src={u.image||"/logo_mark.svg"} alt="" className="h-8 w-8 rounded-full object-cover"/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{u.name}</span><span className="block truncate text-[10px] text-white/30">@{u.username} · {u.email}</span></span><span className="text-[8px] uppercase tracking-[.14em] text-red-300/60">Profile</span></button>)}</div>}</div>
     {section==="content"&&postSuggestions.length>0&&<div className="mb-4 overflow-hidden rounded-2xl border border-white/10 bg-[#0b0b0b] shadow-2xl">{postSuggestions.map((p:any)=><button key={p.id} onClick={()=>{setQ(p.content?.slice(0,80)||p.author.username);setPostSuggestions([]);setSelected(p)}} className="flex w-full items-start gap-3 border-b border-white/[.05] px-4 py-3 text-left last:border-0 hover:bg-white/[.04]"><div className="min-w-0 flex-1"><p className="text-xs font-bold">@{p.author.username}</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-white/40">{p.content||"Media post"}</p></div><span className="text-[8px] uppercase tracking-[.14em] text-red-300/60">Inspect</span></button>)}</div>}
     {section==="users"&&<div className="space-y-2">{(data.users||[]).map((u:any)=><div key={u.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{u.name}</p><p className="truncate text-xs text-white/35">@{u.username} · {u.email}</p></div><span className="shrink-0 text-[9px] font-black uppercase text-red-300">{u.role}</span></div><div className="mt-3 flex flex-wrap gap-2"><Btn onClick={()=>router.push("/users/"+encodeURIComponent(u.username))}>Open profile</Btn><Btn onClick={()=>setSelected(u)}>Manage</Btn><Btn onClick={()=>{setSelected(u);guarded(u.suspendedAt?"restore_user":"suspend_user",u.suspendedAt?"Restore account":"Suspend account")}} danger={!u.suspendedAt}>{u.suspendedAt?"Restore":"Suspend"}</Btn></div></div>)}</div>}
     {section==="content"&&<div className="space-y-5">
      <div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-red-300/70">Community Feed</p><h2 className="mt-1 text-lg font-black">All posts</h2><p className="mt-1 text-[10px] text-white/30">The same content experience as Home, with moderation controls layered on top.</p></div><span className="hidden rounded-full border border-white/[.07] px-3 py-1 text-[9px] text-white/30 sm:inline-flex">{(data.posts||[]).length} loaded</span></div>
      {(data.posts||[]).length===0?<div className="rounded-3xl border border-white/[.08] bg-white/[.025] p-10 text-center text-sm text-white/30">No posts match this search.</div>:<div className="mx-auto w-full max-w-[760px] space-y-5">{(data.posts||[]).map((p:any)=><div key={p.id} className="relative">
        <PostCard post={{id:p.id,content:p.content||"",image:p.image??null,video:p.video??null,createdAt:new Date(p.createdAt).toISOString(),author:p.author,_count:p._count}} publicMode canModerate={superAdmin} onModerateDeleteComment={(commentId)=>{setSelected({id:commentId,content:"Comment moderation"});guarded("delete_comment","Delete comment")}} />
        <div className="mt-2 flex flex-wrap items-center justify-end gap-2"><Link href={`/posts/${encodeURIComponent(p.id)}`} className="rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs font-semibold text-white/60 hover:text-white">Open actual post</Link><Btn onClick={()=>{setSelected(p);guarded("delete_post","Delete post")}} danger>Delete post</Btn></div>
      </div>)}</div>}
    </div>}
    </div>}


    {section==="reports"&&<div className="space-y-2">{(data.reports||[]).map((r:any)=><div key={r.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{r.reason}</p><span className="text-[9px] uppercase text-white/30">{r.status}</span></div><p className="mt-2 text-xs text-white/40">{r.details||"No details provided."}</p><p className="mt-2 text-[10px] text-white/25">Reported by @{r.reporter.username}</p><div className="mt-3 flex gap-2"><Btn onClick={()=>{setSelected(r);act("resolve_report")}}>Resolve</Btn><Btn onClick={()=>{setSelected(r);act("dismiss_report")}}>Dismiss</Btn></div></div>)}</div>}

    {section==="emergencies"&&<div className="space-y-2">{(data.emergencies||[]).map((e:any)=><div key={e.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{e.type}</p><span className="text-[9px] uppercase text-orange-300">{e.status}</span></div><p className="mt-1 text-xs text-white/35">@{e.driver.username} · {e._count.offers} offers</p><p className="mt-2 text-sm text-white/50">{e.description}</p><Btn onClick={()=>{setSelected(e);guarded("close_emergency","Close emergency")}} danger>Close emergency</Btn></div>)}</div>}

    {section==="broadcast"&&<div className="rounded-3xl border border-red-500/15 bg-red-500/[.035] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-red-300">Official Revvam</p><h2 className="mt-2 text-xl font-black">Broadcast center</h2><p className="mt-1 text-xs text-white/35">Send a platform notification to every user without exposing your operations account.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" className="mt-5 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Message" rows={5} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><input value={href} onChange={e=>setHref(e.target.value)} placeholder="Optional link" className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><button disabled={!superAdmin||busy} onClick={()=>act("broadcast_notification",{title,message:body,href:href||null})} className="mt-4 rounded-xl bg-red-600 px-5 py-3 text-xs font-black disabled:opacity-30">{superAdmin?"Broadcast to everyone":"Super Admin only"}</button></div>}

    {section==="governance"&&<div className="space-y-3"><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-red-300">Governance</p><h2 className="mt-2 text-lg font-black">Operational safeguards</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{[["Documented moderation","Destructive moderation requires a reason and is written to the audit log."],["Protected Super Admin","The sole SUPER_ADMIN account cannot be suspended or deleted through God Mode."],["No credential access","Passwords, password hashes and session tokens are never exposed in the console."],["Notification transparency","Broadcasts are clearly marked as official Revvam announcements."],["Audit preservation","Administrative history is append-only from the console."],["Least-privacy principle","The console does not expose private message contents as an administrative shortcut."]].map(([title,desc])=><div key={title} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] leading-4 text-white/30">{desc}</p></div>)}</div><p className="mt-4 text-[10px] leading-4 text-white/25">These technical safeguards reduce operational risk but do not replace Revvam's Terms, Privacy Policy, retention rules, moderation policy or legal advice.</p></div></div>}

    {section==="audit"&&<div className="space-y-2">{(data.logs||[]).map((l:any)=><div key={l.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex justify-between gap-3"><b className="text-xs">{l.action}</b><time className="text-[9px] text-white/20">{new Date(l.createdAt).toLocaleString()}</time></div><p className="mt-1 text-[10px] text-white/30">by @{l.actor.username}{l.targetUser?" · target @"+l.targetUser.username:""}</p><p className="mt-1 text-xs text-white/35">{l.details||""}</p></div>)}</div>}
   </section>
  </div>

  {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-lg rounded-t-3xl border border-white/10 bg-[#090909] p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.2em] text-red-300">Control</p><h3 className="mt-1 text-lg font-black">{selected.name||selected.content||selected.type||"Selected item"}</h3></div><button onClick={()=>setSelected(null)} className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/50">Close</button></div>
   {selected.username&&<div className="mt-5 space-y-3"><p className="text-xs text-white/45">@{selected.username}</p><p className="text-xs text-white/30">{selected.email}</p><label className="block text-[9px] uppercase tracking-[.16em] text-white/30">Role</label><select value={selected.role} onChange={e=>setSelected({...selected,role:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm"><option value="USER">USER</option><option value="MECHANIC">MECHANIC</option><option value="MECHANIC_SHOP">MECHANIC_SHOP</option><option value="DEALERSHIP">DEALERSHIP</option><option value="ADMIN">ADMIN</option><option value="SUPER_ADMIN">SUPER_ADMIN</option></select><input value={selected.name||""} onChange={e=>setSelected({...selected,name:e.target.value})} placeholder="Name" className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm"/><textarea value={selected.bio||""} onChange={e=>setSelected({...selected,bio:e.target.value})} placeholder="Bio" rows={3} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm"/><div className="flex flex-wrap gap-2 pt-1"><Btn onClick={()=>act("update_user",{name:selected.name,bio:selected.bio,role:selected.role})}>Save profile</Btn><Btn onClick={()=>guarded("revoke_sessions","Revoke all sessions")}>Revoke sessions</Btn>{selected.role!=="SUPER_ADMIN"&&<Btn danger onClick={()=>guarded("delete_user","Permanently delete account")}>Delete account</Btn>}</div></div>}
   {selected.content&&<div className="mt-5"><p className="text-sm leading-6 text-white/55">{selected.content}</p>{selected.post&&<p className="mt-2 text-xs text-white/30">Comment on: {selected.post.content||"Media post"}</p>}<Btn danger onClick={()=>guarded(selected.post?"delete_comment":"delete_post",selected.post?"Delete comment":"Delete post")}>{selected.post?"Delete comment":"Delete post"}</Btn></div>}
  </div></div>}

  {confirm&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 p-4"><div className="w-full max-w-sm rounded-3xl border border-red-500/20 bg-[#090909] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-red-300">Confirm action</p><h3 className="mt-2 text-lg font-black">{confirm.label}</h3><p className="mt-2 text-xs leading-5 text-white/35">This action is recorded in the Revvam audit log. Use platform rules consistently, document the factual reason, and avoid changing private credentials or using moderation tools for personal disputes.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required reason (minimum 8 characters)" rows={3} className="mt-4 w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-xs text-white outline-none"/><div className="mt-5 flex gap-2"><Btn danger disabled={busy||reason.trim().length<8} onClick={()=>act(confirm.action)}>{busy?"Working...":"Confirm"}</Btn><Btn onClick={()=>setConfirm(null)}>Cancel</Btn></div></div></div>}
  {message&&<div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-full border border-white/10 bg-[#111]/95 px-4 py-2 text-xs text-white/70 shadow-xl">{message}</div>}
 </div>
}