"use client";

import { useEffect, useState } from "react";

const sections = [["overview","Overview"],["users","Users"],["content","Posts"],["comments","Comments"],["reports","Reports"],["emergencies","Emergencies"],["broadcast","Broadcast"],["audit","Audit"]] as const;
type Section=typeof sections[number][0];

function Btn({children,onClick,danger=false,disabled=false}:{children:any;onClick:()=>void;danger?:boolean;disabled?:boolean}){
 return <button disabled={disabled} onClick={onClick} className={danger?"rounded-lg border border-red-500/20 bg-red-500/[.06] px-3 py-2 text-xs font-semibold text-red-200 disabled:opacity-30":"rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs font-semibold text-white/65 hover:text-white disabled:opacity-30"}>{children}</button>
}

export default function ControlCenterClient({initialStats,superAdmin}:{initialStats:any;superAdmin:boolean}){
 const [section,setSection]=useState<Section>("overview"); const [data,setData]=useState<any>({stats:initialStats});
 const [q,setQ]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const [selected,setSelected]=useState<any>(null); const [confirm,setConfirm]=useState<{action:string;label:string}|null>(null);
 const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [href,setHref]=useState("");

 async function load(s=section){const r=await fetch("/api/control-center?section="+s+(q?"&q="+encodeURIComponent(q):""),{cache:"no-store"});setData(await r.json());}
 useEffect(()=>{void load()},[section]);

 async function act(action:string,extra:any={}){
  setBusy(true);setMessage("Working...");
  const r=await fetch("/api/control-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,targetId:selected?.id,...extra})});
  const d=await r.json();setMessage(r.ok?(d.sent?"Sent to "+d.sent+" users.":"Done."):(d.error||"Action failed."));
  setBusy(false);setConfirm(null);setSelected(null);if(r.ok)void load();
 }
 function guarded(action:string,label:string){setConfirm({action,label});}

 return <div className="mt-7">
  <div className="grid gap-5 lg:grid-cols-[190px_1fr]">
   <aside className="lg:sticky lg:top-6 lg:h-fit">
    <div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-2">
     <p className="px-3 pb-2 pt-2 text-[9px] font-black uppercase tracking-[.2em] text-red-300/60">Command</p>
     {sections.map(([id,label])=><button key={id} onClick={()=>{setSection(id);setSelected(null)}} className={section===id?"mb-1 flex w-full items-center rounded-xl bg-red-500/10 px-3 py-2.5 text-left text-xs font-bold text-red-100":"mb-1 flex w-full items-center rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-white/40 hover:bg-white/[.04] hover:text-white"}>{label}</button>)}
    </div>
    <div className="mt-3 rounded-2xl border border-red-500/15 bg-red-500/[.035] p-4"><p className="text-[9px] font-black uppercase tracking-[.18em] text-red-300">Authority</p><p className="mt-2 text-sm font-black">{superAdmin?"SUPER ADMIN":"ADMIN"}</p><p className="mt-1 text-[10px] leading-4 text-white/30">Server-authorized controls with audit logging.</p></div>
   </aside>

   <section className="min-w-0">
    {section==="overview"&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.stats||{}).map(([k,v])=><div key={k} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><p className="text-[9px] uppercase tracking-[.18em] text-white/25">{k}</p><p className="mt-2 text-2xl font-black">{String(v)}</p></div>)}</div><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-sm font-bold">Command overview</p><p className="mt-2 max-w-2xl text-xs leading-5 text-white/35">Manage accounts, content, reports, emergencies, platform announcements and administrative history from one protected console. Destructive actions require confirmation.</p></div></div>}

    {(section==="users"||section==="content")&&<div>
     <div className="mb-4 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(section==="users"?"users":"content")} placeholder={section==="users"?"Search users...":"Search posts or usernames..."} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm outline-none"/><Btn onClick={()=>load(section==="users"?"users":"content")}>Search</Btn></div>
     {section==="users"&&<div className="space-y-2">{(data.users||[]).map((u:any)=><div key={u.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{u.name}</p><p className="truncate text-xs text-white/35">@{u.username} · {u.email}</p></div><span className="shrink-0 text-[9px] font-black uppercase text-red-300">{u.role}</span></div><div className="mt-3 flex flex-wrap gap-2"><Btn onClick={()=>setSelected(u)}>Manage</Btn><Btn onClick={()=>{setSelected(u);guarded(u.suspendedAt?"restore_user":"suspend_user",u.suspendedAt?"Restore account":"Suspend account")}} danger={!u.suspendedAt}>{u.suspendedAt?"Restore":"Suspend"}</Btn></div></div>)}</div>}
     {section==="content"&&<div className="space-y-2">{(data.posts||[]).map((p:any)=><div key={p.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold">@{p.author.username}</p><p className="mt-2 text-sm leading-5 text-white/60">{p.content||"Media post"}</p></div><span className="text-[9px] text-white/25">{p._count.comments} comments</span></div><div className="mt-3 flex gap-2"><Btn onClick={()=>setSelected(p)}>View</Btn><Btn onClick={()=>{setSelected(p);guarded("delete_post","Delete post")}} danger>Delete</Btn></div></div>)}</div>}
    </div>}

    {section==="comments"&&<div><div className="mb-4 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load("comments")} placeholder="Search comments or usernames..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm outline-none"/><Btn onClick={()=>load("comments")}>Search</Btn></div><div className="space-y-2">{(data.comments||[]).map((c:any)=><div key={c.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-xs font-bold">@{c.author.username}</p><p className="mt-2 text-sm leading-5 text-white/55">{c.content}</p><p className="mt-2 line-clamp-1 text-[10px] text-white/25">On: {c.post.content||"Media post"}</p><div className="mt-3 flex gap-2"><Btn onClick={()=>setSelected(c)}>View</Btn><Btn danger onClick={()=>{setSelected(c);guarded("delete_comment","Delete comment")}}>Delete</Btn></div></div>)}</div></div>}

    {section==="reports"&&<div className="space-y-2">{(data.reports||[]).map((r:any)=><div key={r.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{r.reason}</p><span className="text-[9px] uppercase text-white/30">{r.status}</span></div><p className="mt-2 text-xs text-white/40">{r.details||"No details provided."}</p><p className="mt-2 text-[10px] text-white/25">Reported by @{r.reporter.username}</p><div className="mt-3 flex gap-2"><Btn onClick={()=>{setSelected(r);act("resolve_report")}}>Resolve</Btn><Btn onClick={()=>{setSelected(r);act("dismiss_report")}}>Dismiss</Btn></div></div>)}</div>}

    {section==="emergencies"&&<div className="space-y-2">{(data.emergencies||[]).map((e:any)=><div key={e.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{e.type}</p><span className="text-[9px] uppercase text-orange-300">{e.status}</span></div><p className="mt-1 text-xs text-white/35">@{e.driver.username} · {e._count.offers} offers</p><p className="mt-2 text-sm text-white/50">{e.description}</p><Btn onClick={()=>{setSelected(e);guarded("close_emergency","Close emergency")}} danger>Close emergency</Btn></div>)}</div>}

    {section==="broadcast"&&<div className="rounded-3xl border border-red-500/15 bg-red-500/[.035] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-red-300">Official Revvam</p><h2 className="mt-2 text-xl font-black">Broadcast center</h2><p className="mt-1 text-xs text-white/35">Send a platform notification to every user without exposing your operations account.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" className="mt-5 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Message" rows={5} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><input value={href} onChange={e=>setHref(e.target.value)} placeholder="Optional link" className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><button disabled={!superAdmin||busy} onClick={()=>act("broadcast_notification",{title,message:body,href:href||null})} className="mt-4 rounded-xl bg-red-600 px-5 py-3 text-xs font-black disabled:opacity-30">{superAdmin?"Broadcast to everyone":"Super Admin only"}</button></div>}

    {section==="audit"&&<div className="space-y-2">{(data.logs||[]).map((l:any)=><div key={l.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex justify-between gap-3"><b className="text-xs">{l.action}</b><time className="text-[9px] text-white/20">{new Date(l.createdAt).toLocaleString()}</time></div><p className="mt-1 text-[10px] text-white/30">by @{l.actor.username}{l.targetUser?" · target @"+l.targetUser.username:""}</p><p className="mt-1 text-xs text-white/35">{l.details||""}</p></div>)}</div>}
   </section>
  </div>

  {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-lg rounded-t-3xl border border-white/10 bg-[#090909] p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.2em] text-red-300">Control</p><h3 className="mt-1 text-lg font-black">{selected.name||selected.content||selected.type||"Selected item"}</h3></div><button onClick={()=>setSelected(null)} className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/50">Close</button></div>
   {selected.username&&<div className="mt-5 space-y-3"><p className="text-xs text-white/45">@{selected.username}</p><p className="text-xs text-white/30">{selected.email}</p><label className="block text-[9px] uppercase tracking-[.16em] text-white/30">Role</label><select value={selected.role} onChange={e=>setSelected({...selected,role:e.target.value})} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm"><option value="USER">USER</option><option value="MECHANIC">MECHANIC</option><option value="MECHANIC_SHOP">MECHANIC_SHOP</option><option value="DEALERSHIP">DEALERSHIP</option><option value="ADMIN">ADMIN</option><option value="SUPER_ADMIN">SUPER_ADMIN</option></select><input value={selected.name||""} onChange={e=>setSelected({...selected,name:e.target.value})} placeholder="Name" className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm"/><textarea value={selected.bio||""} onChange={e=>setSelected({...selected,bio:e.target.value})} placeholder="Bio" rows={3} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm"/><div className="flex flex-wrap gap-2 pt-1"><Btn onClick={()=>act("update_user",{name:selected.name,bio:selected.bio,role:selected.role})}>Save profile</Btn><Btn onClick={()=>guarded("revoke_sessions","Revoke all sessions")}>Revoke sessions</Btn>{selected.role!=="SUPER_ADMIN"&&<Btn danger onClick={()=>guarded("delete_user","Permanently delete account")}>Delete account</Btn>}</div></div>}
   {selected.content&&<div className="mt-5"><p className="text-sm leading-6 text-white/55">{selected.content}</p>{selected.post&&<p className="mt-2 text-xs text-white/30">Comment on: {selected.post.content||"Media post"}</p>}<Btn danger onClick={()=>guarded(selected.post?"delete_comment":"delete_post",selected.post?"Delete comment":"Delete post")}>{selected.post?"Delete comment":"Delete post"}</Btn></div>}
  </div></div>}

  {confirm&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 p-4"><div className="w-full max-w-sm rounded-3xl border border-red-500/20 bg-[#090909] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-red-300">Confirm action</p><h3 className="mt-2 text-lg font-black">{confirm.label}</h3><p className="mt-2 text-xs leading-5 text-white/35">This action is recorded in the Revvam audit log. Destructive actions cannot be undone.</p><div className="mt-5 flex gap-2"><Btn danger disabled={busy} onClick={()=>act(confirm.action)}>{busy?"Working...":"Confirm"}</Btn><Btn onClick={()=>setConfirm(null)}>Cancel</Btn></div></div></div>}
  {message&&<div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-full border border-white/10 bg-[#111]/95 px-4 py-2 text-xs text-white/70 shadow-xl">{message}</div>}
 </div>
}