ALTER TABLE "EmergencyRequest" ADD COLUMN IF NOT EXISTS "ghostMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EMERGENCY_OFFER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EMERGENCY_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EMERGENCY_DECLINED';
